apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    name: app
spec:
  replicas: 3
  selector:
    matchLabels:
      name: app
  template:
    metadata:
      labels:
        name: app
    spec:
      containers:
        - name: app
          image: voylovbogdan/devops-lab3:latest
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 3000
            failureThreshold: 1
            periodSeconds: 10
        - name: nginx
          image: nginx:1.23.4-alpine3.17
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /etc/nginx/conf.d
              name: nginx-conf
          args: [
           "-g",
            "daemon off;",
          ]
      volumes:
        - name: nginx-conf
          configMap:
            name: nginx